### ISSUE TITLE
RNfirebase v6 dont recieve notification in background

### ISSUE THREAD

**Issue by daymanondev** [0x1bitcrack3r/RNFirebaseCallNotifications#1]
I'm using RNfirebase v6, but in file AndroidManifest dont have io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService. I'm only use io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService for service and receiver but in ViAuFirebaseMessagingService not recieve notification in backgrond state. 

When i push a notification to device in background state
![image](https://user-images.githubusercontent.com/39049115/115754118-18365c80-a3c6-11eb-9f61-9ff800599beb.png)
Then i add setBackgroundMessageHandler in React Native code, but ViAuFirebaseMessagingService not recieve notification

My AndroidMenifest
![image](https://user-images.githubusercontent.com/39049115/115754424-5e8bbb80-a3c6-11eb-82d7-2730118a68e0.png)

Do you have solution for me?
Thank you so much 👍👍👍

**Comment by BoobalanK** [comment]
Hey @dungpasoftware , Please can you let me know how did you solved the issue ?
