### ISSUE TITLE
How can we remove accept and reject button after a specific amount of time

### ISSUE THREAD

**Issue by emanu7478** [0x1bitcrack3r/RNFirebaseCallNotifications#2]
We want to make the call missed after a specific amount of time. So that user may not be able to attend the call at that time.

**Comment by 0x1bitcrack3r** [comment]
You can set timmer from the source and send an end call notification message. And listen to the end call notification message on the Android app end and quit the call when you receive that message.

**Comment by 0x1bitcrack3r** [comment]
closing this issue @emanu7478
